dbconf:
  name: "finaltest"
  #uri: "mongodb://campus:campus@qiuyuhan.xyz:27017/test"
  uri: "mongodb://root:yh-qiu18@qiuyuhan.xyz:27017"
hostconf:

  #domain: "localhost"
  domain: "qiuyuhan.xyz"
  #domain: "10.0.2.2"
  # Windows
  #static: "D:\\workPlace\\Android\\test"

  # Ubuntu
  static: "/home/ubuntu/static"

  # MacOS
  # static: "/Users/bytedance/Documents/"
