dbconf:
  name: "test"
  uri: "mongodb://campus:campus@qiuyuhan.xyz:27017/test"

hostconf:
  #domain: "localhost"
  domain: "10.0.2.2"
  static: "D:\\workPlace\\Android\\test"
# static: "/Users/bytedance/Documents/"
